json.id resource.id
json.codigo resource.codigo
json.nombre resource.nombre
json.descripcion resource.descripcion
json.descripcion_larga resource.descripcion_larga
json.categoria resource.categoria
json.subcategoria resource.subcategoria
json.precio resource.precio
json.moneda resource.moneda
json.unidad_medida resource.unidad_medida
json.presentacion resource.presentacion
json.stock_disponible resource.stock_disponible
json.stock_minimo resource.stock_minimo
json.descuento resource.descuento
json.precio_oferta resource.precio_oferta
json.impuesto resource.impuesto
json.estado resource.estado
json.marca resource.marca
json.proveedor resource.proveedor
json.codigo_barras resource.codigo_barras
json.imagen_url resource.imagen_url
json.galeria_imagenes resource.galeria_imagenes
json.ficha_tecnica_url resource.ficha_tecnica_url
json.manual_url resource.manual_url
json.video_url resource.video_url
json.pais_origen resource.pais_origen
json.garantia resource.garantia
json.fecha_creacion resource.fecha_creacion
json.fecha_actualizacion resource.fecha_actualizacion
json.etiquetas resource.etiquetas
json.politicas_envio resource.politicas_envio
json.politicas_devolucion resource.politicas_devolucion
json.variantes resource.variantes
json.relacionados resource.relacionados
json.ratings resource.ratings
json.account_id resource.account_id
json.agent_bot_id resource.agent_bot_id
json.created_at resource.created_at
json.updated_at resource.updated_at
